# this file is to be used to debug GSDK calls to sidecar
version: '3'
services:
    sidecar:
        restart: always
        build:
            dockerfile: Dockerfile
            context: ./sidecar-go
        ports:
          - '56001:56001'
        environment:
          - PF_GAMESERVER_NAME=randomGameServerName
          - PF_GAMESERVER_NAMESPAME=default
    sample_netcore:
        environment:
          - GSDK_CONFIG_FILE=/data/Config/gsdkConfig.json
          - PF_REGION=WestUs
          - PUBLIC_IPV4_ADDRESS=20.184.250.154
          - PF_VM_ID=xcloudwus4u4yz5dlozul:WestUs:6b5973a5-a3a5-431a-8378-eff819dc0c25:tvmps_efa402aacd4f682230cfd91bd3dc0ddfae68c312f2b6905577cb7d9424681930_d
          - PF_SHARED_CONTENT_FOLDER=/data/GameSharedContent
          - PF_SERVER_INSTANCE_NUMBER=2
          - PF_BUILD_ID=88a958b9-14fb-4ad9-85ca-5cc13207232e
          - CERTIFICATE_FOLDER=/data/GameCertificates
          - PF_SERVER_LOG_DIRECTORY=/data/GameLogs/
          - PF_TITLE_ID=1E03
          - ASPNETCORE_ENVIRONMENT=Development
        restart: always
        build:
          dockerfile: Dockerfile
          context: ./samples/netcore
        volumes: 
          - ./samples/data:/data